/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rpg;

/**
 *
 * @author Denise
 */
public class HabsOurProfi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HabsOurProfi.class.getName());

    /**
     * Creates new form Classe
     */
    public HabsOurProfi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        check2Blade = new javax.swing.JCheckBox();
        checkMagia = new javax.swing.JCheckBox();
        checkFurtividade = new javax.swing.JCheckBox();
        checkCura = new javax.swing.JCheckBox();
        checkIntimidate = new javax.swing.JCheckBox();
        btnProx = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Habilidades ou Proficiências");

        check2Blade.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        check2Blade.setForeground(new java.awt.Color(255, 0, 0));
        check2Blade.setText("Ataque com duas armas");

        checkMagia.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        checkMagia.setForeground(new java.awt.Color(0, 204, 255));
        checkMagia.setText("Magia arcana");

        checkFurtividade.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        checkFurtividade.setForeground(new java.awt.Color(153, 153, 153));
        checkFurtividade.setText("Furtividade");
        checkFurtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFurtividadeActionPerformed(evt);
            }
        });

        checkCura.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        checkCura.setForeground(new java.awt.Color(51, 255, 51));
        checkCura.setText("Cura");
        checkCura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCuraActionPerformed(evt);
            }
        });

        checkIntimidate.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        checkIntimidate.setForeground(new java.awt.Color(255, 255, 255));
        checkIntimidate.setText("Intimidação");
        checkIntimidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIntimidateActionPerformed(evt);
            }
        });

        btnProx.setBackground(new java.awt.Color(51, 51, 255));
        btnProx.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        btnProx.setText("Proximo -->");
        btnProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkIntimidate)
                    .addComponent(checkCura)
                    .addComponent(checkFurtividade)
                    .addComponent(checkMagia)
                    .addComponent(check2Blade)
                    .addComponent(jLabel1))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProx)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(check2Blade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkMagia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkFurtividade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkCura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkIntimidate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btnProx)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkFurtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFurtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkFurtividadeActionPerformed

    private void checkCuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCuraActionPerformed

    private void checkIntimidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIntimidateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkIntimidateActionPerformed

    private void btnProxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProxActionPerformed
        
    }//GEN-LAST:event_btnProxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HabsOurProfi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProx;
    private javax.swing.JCheckBox check2Blade;
    private javax.swing.JCheckBox checkCura;
    private javax.swing.JCheckBox checkFurtividade;
    private javax.swing.JCheckBox checkIntimidate;
    private javax.swing.JCheckBox checkMagia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
