/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.selecaohogwarts;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JOAOPEDRODESBESELAPP
 */
public class Selecao extends javax.swing.JFrame {
private DefaultTableModel tableSelect;
private DefaultTableModel tableGriffinoriaG;
private DefaultTableModel tableSonserinaS;
private DefaultTableModel tableLufaL;
private DefaultTableModel tableCorvinalC;
    /**
     * Creates new form Selecao
     */
    public Selecao() {
        initComponents();
        tableSonserinaS = new DefaultTableModel();
        tableSelect = new DefaultTableModel();
        tableGriffinoriaG = new DefaultTableModel();
        tableLufaL = new DefaultTableModel();
        tableCorvinalC = new DefaultTableModel();
        
        
        tableSelect.addColumn("Nome"); // adiciona uma coluna, ja com o titulo
        tableSelect.addColumn("Personalidade");
        
        tableGriffinoriaG.addColumn("Nome");
        tableGriffinoriaG.addColumn("Personalidade");
        
        tableSonserinaS.addColumn("Nome");
        tableSonserinaS.addColumn("Personalidade");
        
        tableLufaL.addColumn("Nome");
        tableLufaL.addColumn("Personalidade");
        
        tableCorvinalC.addColumn("Nome");
        tableCorvinalC.addColumn("Personalidade");

        
        
        
        tableSelect.addRow(new Object[]{"Roberto Carlos","Amigavel"});//adiciona uma linha, com os valores
        tableSelect.addRow(new Object[]{"Draco","Maldoso"});
        tableSelecao.setModel(tableSelect);
        tableGriffin.setModel(tableGriffinoriaG);
        tableSonserina.setModel(tableSonserinaS);
        tableLufa.setModel(tableLufaL);
        tableCorvinal.setModel(tableCorvinalC);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSelecao = new javax.swing.JTable();
        btnChapeuSeletor = new javax.swing.JButton();
        btnExpulsar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSonserina = new javax.swing.JTable();
        labelG = new javax.swing.JLabel();
        labelS = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableLufa = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableGriffin = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableCorvinal = new javax.swing.JTable();
        labelL = new javax.swing.JLabel();
        labelC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        tableSelecao.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        tableSelecao.setForeground(new java.awt.Color(0, 0, 0));
        tableSelecao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableSelecao);

        btnChapeuSeletor.setBackground(new java.awt.Color(0, 0, 204));
        btnChapeuSeletor.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnChapeuSeletor.setForeground(new java.awt.Color(0, 0, 0));
        btnChapeuSeletor.setText("Chapéu Seletor");
        btnChapeuSeletor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChapeuSeletorActionPerformed(evt);
            }
        });

        btnExpulsar.setBackground(new java.awt.Color(255, 0, 0));
        btnExpulsar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnExpulsar.setForeground(new java.awt.Color(0, 0, 0));
        btnExpulsar.setText("Expulsar");
        btnExpulsar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpulsarActionPerformed(evt);
            }
        });

        tableSonserina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableSonserina);

        labelG.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelG.setForeground(new java.awt.Color(255, 255, 255));
        labelG.setText("Alunos da Griffinória: ");

        labelS.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelS.setForeground(new java.awt.Color(255, 255, 255));
        labelS.setText("Alunos da Sonserina:");

        tableLufa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableLufa);

        tableGriffin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tableGriffin);

        tableCorvinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Personalidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableCorvinal);

        labelL.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelL.setForeground(new java.awt.Color(255, 255, 255));
        labelL.setText("Alunos da Lufa-Lufa:");

        labelC.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        labelC.setForeground(new java.awt.Color(255, 255, 255));
        labelC.setText("Alunos da Corvinal:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnChapeuSeletor, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnExpulsar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelG)
                                        .addComponent(labelL))
                                    .addGap(214, 214, 214)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelS)
                                        .addComponent(labelC)))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(386, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChapeuSeletor)
                    .addComponent(btnExpulsar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelG)
                    .addComponent(labelS))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelL)
                    .addComponent(labelC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(284, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(243, 243, 243)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExpulsarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpulsarActionPerformed
        int linha = tableSelecao.getSelectedRow();
if (linha != -1) {
    tableSelect.removeRow(linha);
    
    int linha1 = tableSelecao.getSelectedRow();
if (linha1 != -1) {
    tableSelect.removeRow(linha1);
}   
    }
    }//GEN-LAST:event_btnExpulsarActionPerformed

    private void btnChapeuSeletorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChapeuSeletorActionPerformed
         int index = tableSelecao.getSelectedRow();

    // Se nenhuma linha estiver selecionada, exibe mensagem e sai
    if (index == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma pessoa da lista.");
        return;
    }

    String nome = tableSelecao.getValueAt(index, 0).toString();
    String personalidade = tableSelecao.getValueAt(index, 1).toString().toLowerCase();

    switch (personalidade) {
        case "amigavel":
            tableGriffinoriaG.addRow(new Object[]{nome, personalidade});
            break;
        case "maldoso":
            tableSonserinaS.addRow(new Object[]{nome, personalidade});
            break;
        case "inteligente":
            tableCorvinalC.addRow(new Object[]{nome, personalidade});
            break;
        case "leal":
            tableLufaL.addRow(new Object[]{nome, personalidade});
            break;
        default:
            JOptionPane.showMessageDialog(this, "Opção inválida!");
    }

    // opcional: remove da tabela de seleção
    ((DefaultTableModel) tableSelecao.getModel()).removeRow(index);
        
        labelG.setText("Alunos da Griffinória:" + tableGriffin.getRowCount());
        labelS.setText("Alunos da Sonserina:" + tableSonserina.getRowCount());
        labelL.setText("Alunos da Lufa-Lufa:" + tableLufa.getRowCount());
        labelC.setText("Alunos da Corvinal:" + tableCorvinal.getRowCount());
        
    }//GEN-LAST:event_btnChapeuSeletorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChapeuSeletor;
    private javax.swing.JButton btnExpulsar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel labelC;
    private javax.swing.JLabel labelG;
    private javax.swing.JLabel labelL;
    private javax.swing.JLabel labelS;
    private javax.swing.JTable tableCorvinal;
    private javax.swing.JTable tableGriffin;
    private javax.swing.JTable tableLufa;
    private javax.swing.JTable tableSelecao;
    private javax.swing.JTable tableSonserina;
    // End of variables declaration//GEN-END:variables
}
