/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacegrafica;

/**
 *
 * @author JOAOPEDRODESBESELAPP
 */
public class TelaINT01 extends javax.swing.JFrame {

    /**
     * Creates new form TelaINT01
     */
    public TelaINT01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textNumb1 = new javax.swing.JTextField();
        textNumb2 = new javax.swing.JTextField();
        btnSoma = new javax.swing.JButton();
        btnMultiplicação = new javax.swing.JButton();
        btnDivisão = new javax.swing.JButton();
        btnSubtração = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        textNumb1.setBackground(new java.awt.Color(153, 0, 0));
        textNumb1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textNumb1.setForeground(new java.awt.Color(0, 0, 0));
        textNumb1.setText("Insira o numero 1:");
        textNumb1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textNumb1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNumb1FocusLost(evt);
            }
        });
        textNumb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumb1ActionPerformed(evt);
            }
        });

        textNumb2.setBackground(new java.awt.Color(255, 255, 0));
        textNumb2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        textNumb2.setForeground(new java.awt.Color(0, 0, 0));
        textNumb2.setText("Insira o numero 2:");
        textNumb2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textNumb2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNumb2FocusLost(evt);
            }
        });
        textNumb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumb2ActionPerformed(evt);
            }
        });

        btnSoma.setBackground(new java.awt.Color(255, 255, 255));
        btnSoma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSoma.setForeground(new java.awt.Color(0, 0, 0));
        btnSoma.setText("Soma");
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });

        btnMultiplicação.setBackground(new java.awt.Color(153, 102, 0));
        btnMultiplicação.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMultiplicação.setForeground(new java.awt.Color(0, 0, 0));
        btnMultiplicação.setText("Multiplicação");
        btnMultiplicação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicaçãoActionPerformed(evt);
            }
        });

        btnDivisão.setBackground(new java.awt.Color(51, 51, 51));
        btnDivisão.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDivisão.setForeground(new java.awt.Color(0, 0, 0));
        btnDivisão.setText("Divisão");
        btnDivisão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisãoActionPerformed(evt);
            }
        });

        btnSubtração.setBackground(new java.awt.Color(204, 255, 204));
        btnSubtração.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubtração.setForeground(new java.awt.Color(0, 0, 0));
        btnSubtração.setText("Subtração");
        btnSubtração.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtraçãoActionPerformed(evt);
            }
        });

        labelResultado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        labelResultado.setForeground(new java.awt.Color(0, 0, 0));
        labelResultado.setText("Resultado:");

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Calculatora Simulator X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSoma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubtração, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivisão, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMultiplicação, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textNumb1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNumb2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(textNumb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNumb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnSoma)
                .addGap(18, 18, 18)
                .addComponent(btnSubtração)
                .addGap(18, 18, 18)
                .addComponent(btnDivisão)
                .addGap(18, 18, 18)
                .addComponent(btnMultiplicação)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelResultado)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNumb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumb1ActionPerformed

    private void textNumb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumb2ActionPerformed

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomaActionPerformed
        Double numb1 = Double.parseDouble(textNumb1.getText());
        Double numb2 = Double.parseDouble(textNumb2.getText());
        labelResultado.setText("Resultado:" + (numb1 + numb2));
    }//GEN-LAST:event_btnSomaActionPerformed

    private void btnMultiplicaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicaçãoActionPerformed
        Double numb1 = Double.parseDouble(textNumb1.getText());
        Double numb2 = Double.parseDouble(textNumb2.getText());
        labelResultado.setText("Resultado:" + (numb1 * numb2));
    }//GEN-LAST:event_btnMultiplicaçãoActionPerformed

    private void btnDivisãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisãoActionPerformed
        Double numb1 = Double.parseDouble(textNumb1.getText());
        Double numb2 = Double.parseDouble(textNumb2.getText());
        labelResultado.setText("Resultado:" + (numb1 / numb2));
    }//GEN-LAST:event_btnDivisãoActionPerformed

    private void btnSubtraçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtraçãoActionPerformed
        Double numb1 = Double.parseDouble(textNumb1.getText());
        Double numb2 = Double.parseDouble(textNumb2.getText());
        labelResultado.setText("Resultado:" + (numb1 - numb2));
    }//GEN-LAST:event_btnSubtraçãoActionPerformed
private static final String PLACEHOLDER1 = "Insira o numero 1:";
    private void textNumb1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNumb1FocusGained
        if (textNumb1.getText().equals(PLACEHOLDER1)) {
        textNumb1.setText("");
        }
    }//GEN-LAST:event_textNumb1FocusGained

    private void textNumb1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNumb1FocusLost
        if(textNumb1.getText().isEmpty()){
            textNumb1.setText(PLACEHOLDER1);
        }
    }//GEN-LAST:event_textNumb1FocusLost
private static final String PLACEHOLDER2 = "Insira o numero 2:";

    private void textNumb2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNumb2FocusGained
        if(textNumb2.getText().equals(PLACEHOLDER2)){
            textNumb2.setText("");
        }
    }//GEN-LAST:event_textNumb2FocusGained

    private void textNumb2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNumb2FocusLost
        if(textNumb2.getText().isEmpty()){
            textNumb2.setText(PLACEHOLDER2);
        }
    }//GEN-LAST:event_textNumb2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaINT01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaINT01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaINT01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaINT01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaINT01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivisão;
    private javax.swing.JButton btnMultiplicação;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnSubtração;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextField textNumb1;
    private javax.swing.JTextField textNumb2;
    // End of variables declaration//GEN-END:variables
}
